### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by BriSyWill** [Hyperparticle/nodulus#1]
Hey, not so much an issue as it is a few questions and intros. 

My name is Bri, and I'm a game design intern at the Wilson Center in D.C. We're currently working on a game that involves cyber security, and we'd like to use your game nodulus as a mini game inside it (with credit going to you and the MIT License staying in tact). I just wanted to double check that this is okay with you. 
If that is the case, would you happen to have documentation as to how to make individual levels? Your game would pop in between moments of dialog and we'd like it so that one level would appear at a time (I can explain further if need be). 

Thanks so much!
Bri Williams

**Comment by Hyperparticle** [comment]
Hello, using this game in another project would be cool. As Nodulus is MIT licensed, any part of the code or assets are free to use.

It's important to keep in mind that Nodulus runs in the Unity game engine, so embedding it in another game would very likely require the other game to run in Unity. What technologies are you using for your game? Also, do you have performance/resource constraints? For instance, running on in mobile device app is different from running in a desktop browser window.

I don't have documentation (yet) on how to create custom levels, but I made sure it's pretty simple to do. All you need is to edit a text file. I can update the wiki as necessary. Running different levels at different points in time should be simple, but I need more information on the tech of the base game (e.g., programming language, operating system, frameworks).

Thank you for your comment, and good luck on your game.

**Comment by BriSyWill** [comment]
We're also using Unity to make our game so that's not a problem. Our game will be running inside a web browser, and server space isn't quite an issue.

**Comment by Hyperparticle** [comment]
So I assume you're using WebGL? I've tested the game with WebGL on the desktop and it runs fine. I will have a WebGL build running once the game releases very soon.

Are you able to open the game in Unity (requires 2017.1.0+, as it uses C# 6)? The main scene is located under [Assets/Scenes/NodulusGame.unity](https://github.com/Hyperparticle/nodulus/blob/master/Assets/Scenes/NodulusGame.unity). If so, the first thing to test would be to run the scene alongside your main scene with [Multi Scene Editing](https://docs.unity3d.com/Manual/MultiSceneEditing.html).

**Comment by BriSyWill** [comment]
Yes, we are using WebGL and we are using is the latest version of Unity. The main concern I have right now is that when I import your game as a package into mine, most of the yaml syntax get's lost in transfer. Could you clarify what collections you use when concerning yaml (the using parameters in the script). 

And I just wanted to say, thanks again for all your help! I really appreciate it.

**Comment by Hyperparticle** [comment]
I'm not sure what you mean by yaml. Are you referring to the yaml file [Assets/Resources/BeginnerLevels.yaml](https://github.com/Hyperparticle/nodulus/blob/master/Assets/Resources/Levels/BeginnerLevels.yaml)? Or are you referring to the Unity scene files? I'm using the YamlDotNet for Unity from the asset store to parse yaml files.

I'm perfectly happy to help!

**Comment by BriSyWill** [comment]
Ohhhh okay, it was the YamlDotNet asset that was causing some issues on my end. I think not having it installed made my scenes go haywire. I'll install it and work from there.

**Comment by Hyperparticle** [comment]
Do you still wish to pursue integrating Nodulus into your project? I'm happy to help if you still do.
