### ISSUE TITLE
Version glitch?

### ISSUE THREAD

**Issue by david-pfx** [Hyperparticle/nodulus#4]
Loaded on 2018.3.7f1:

Assets\PostProcessing\Editor\PropertyDrawers\MinDrawer.cs(6,34): error CS0104: 'MinAttribute' is an ambiguous reference between 'UnityEngine.PostProcessing.MinAttribute' and 'UnityEngine.MinAttribute'

**Comment by Hyperparticle** [comment]
Looks like `MinAttribute` has been placed in a different namespace in newer versions of Unity. Have you tried changing the import in `MinDrawer.cs` to `UnityEngine.MinAttribute` or `UnityEngine.PostProcessing.MinAttribute`? Does either one work?

**Comment by david-pfx** [comment]
Yes, they both work. Your choice.

**Comment by Hyperparticle** [comment]
Finally got around to fixing this. :satisfied:
