### ISSUE TITLE
Options dialog does not open

### ISSUE THREAD

**Issue by david-pfx** [Hyperparticle/nodulus#5]
The game runs just fine in the Editor, but clicking on the menu button does nothing.

It's ancient OnGUI code, which I have never used and would rather not, so no idea what's causing it. The best solution would be to convert it to the newer GUI.

**Comment by Hyperparticle** [comment]
Which menu button are you referring to?

**Comment by david-pfx** [comment]
This one.
![menu](https://user-images.githubusercontent.com/12763741/56703493-6e775300-674c-11e9-8568-3416cda778c5.png)

**Comment by Hyperparticle** [comment]
Quite strange, but I'll have to check it out with your version. It's `2018.3.7f1`, correct? Any helpful error output?

**Comment by david-pfx** [comment]
My bad. Yes, Null Object Exception at Scrollview 232.

The bug is simple: two game objects with the same tag: NavigationPanel and Navigation. Remove the tag from the panel and it all works just fine.

Version differences in non-deterministic behaviour, a common problem in Unity. Hard to avoid, simple to fix.

**Comment by Hyperparticle** [comment]
Thank you so much for your help! I'll submit a fix for this when I get around to it.
