### ISSUE TITLE
Add to f-droid

### ISSUE THREAD

**Issue by 532910** [Hyperparticle/nodulus#7]
Please add it to F-Droid

https://gitlab.com/fdroid/rfp

**Comment by 532910** [comment]
https://gitlab.com/fdroid/rfp/issues/1084

Could you confirm, that: 
> The original app author has been notified (and supports the inclusion).

?

**Comment by Hyperparticle** [comment]
I support the inclusion to f-droid. I'm not sure if there may be issues with dependencies to Unity3D, though. Anything I need to do on my part?

**Comment by 532910** [comment]
Could you clarify the license of Unity3D?

**Comment by Hyperparticle** [comment]
The [Unity3D Terms of Service](https://unity3d.com/legal/terms-of-service) indicates all intellectual rights for the code and assets I created are mine (which is currently MIT licensed), so I believe no problems there. The only thing is that it requires Unity3D (proprietary) to compile everything.

**Comment by 532910** [comment]
> requires Unity3D (proprietary)

Sorry, unfortunately it can't be included into F-Droid.
